#!/bin/sh
#easier way how to handle version formats  https://safrm.net/projects/appver
#author:  Miroslav Safr <miroslav.safr@gmail.com>
VERSION=NA
VERSION_DATE=NA

#defaults
APP_FULL_VERSION_TAG=NA
APP_SHORT_VERSION_TAG=NA
APP_BUILD_DATE=NA

#version can be forced by argument for packaging builds
if [ -z "$1" ]; then
    APP_FULL_VERSION_TAG=`git describe --tags --dirty=* 2> /dev/null | sed 's/-[^-]\+$$//' | sed 's/-/_/g'`
    APP_SHORT_VERSION_TAG=`git describe --abbrev=0 2> /dev/null | sed 's/-[^-]\+$$//' | sed 's/-/_/g'`
else
    APP_FULL_VERSION_TAG="$1"
    APP_SHORT_VERSION_TAG="$APP_FULL_VERSION_TAG"
fi
APP_BUILD_DATE=`date +'%Y%m%d_%H%M'`

echo "APP_FULL_VERSION_TAG=$APP_FULL_VERSION_TAG"
echo "APP_SHORT_VERSION_TAG=$APP_SHORT_VERSION_TAG"
echo "APP_BUILD_DATE=$APP_BUILD_DATE"

#combinations
APP_FULL_VERSION_AND_DATE="$APP_FULL_VERSION_TAG ($APP_BUILD_DATE)"

export APP_FULL_VERSION_TAG=$APP_FULL_VERSION_TAG
export APP_SHORT_VERSION_TAG=$APP_SHORT_VERSION_TAG
export APP_BUILD_DATE=$APP_BUILD_DATE
export APP_FULL_VERSION_AND_DATE="$APP_FULL_VERSION_AND_DATE"
