#!/bin/sh
#easier way how to handle development installations http://safrm.net/projects/appver/
#author:  Miroslav Safr <miroslav.safr@gmail.com>
BINDIR=/usr/bin
COMPLETION_DIR=/etc/bash_completion.d
MANDIR=/usr/share/man

fail() { printf "\n\033[01;31mERROR: $*\033[00m\n" ; exit 1 ; }
verbose() { [ ${VERBOSE_FLAG:-0 } -eq 0 ] || echo "\033[36m$*\033[00m" ; }
appver_basic_usage() {
    echo " Usage: `basename $0` [OPTIONS]  Development installer"
    echo " OPTIONS:"
    echo "          -v, --verbose............... verbose"
    echo "          -h, --help.................. prints help"
}
appver_update_version_and_date() {
if [ -n "$1" ]; then
    sed -i".bkp" "1,/^VERSION=/s/^VERSION=.*/VERSION=$APP_FULL_VERSION_TAG/" "$1" && rm -f "$1".bkp
    sed -i".bkp" "1,/^VERSION_DATE=/s/^VERSION_DATE=.*/VERSION_DATE=$APP_BUILD_DATE/" "$1" && rm -f "$1".bkp
fi
}
appver_command_exists() {
    command -v "$1" 1>/dev/null 2>&1 ;
}

appver_basic_scripts_test() {
    for TEST in $( grep -r -l -h "#\!/bin/sh" --exclude-dir=.git --exclude-dir=test . )
    do
        sh -n "$TEST"
        if  [ $? != 0 ]; then
            fail "syntax error in $TEST, exiting.."
        fi
    done
}

#root check
[ `id -u` -ne 0 ] && [ `uname -s | grep -i linux` ] &&
    fail "Cannot continue, you should be root or run it with sudo!"

#install commands
if appver_command_exists install ; then
    MKDIR_755="mkdir -p -m 0755 "
    INSTALL_755="install -m 0755 -v "
    INSTALL_644="install -m 0644 -v "
else
    MKDIR_755="mkdir -p "
    INSTALL_755="cp -afv "
    INSTALL_644="$INSTALL_755"
fi

#automatic version
if appver_command_exists appver ; then
    . appver
else
    [ -z "$APP_SHORT_VERSION" ] && APP_SHORT_VERSION=NA
    [ -z "$APP_FULL_VERSION_TAG" ] && APP_FULL_VERSION_TAG=NA
    [ -z "$APP_BUILD_DATE" ] && APP_BUILD_DATE=`date +'%Y%m%d_%H%M'`
fi

#update documentation
if appver_command_exists jss-docs-update ; then
    jss-docs-update ./doc
fi

#auto install man pages
MANPAGES=`find ./doc/manpages -type f`
if [ -n "$MANPAGES" ]; then
    mkdir -p -m 775 $MANDIR/man1
    $INSTALL_644 $MANPAGES $MANDIR/man1
fi

